import Link from 'next/link';import Image from 'next/image';import {ArrowRight,BadgePercent,CalendarClock,Link2,MapPin,MessageCircle,ShieldCheck,TrainFront,Truck} from 'lucide-react';import {Catalog} from '@/components/catalog';
const steps=[[ShieldCheck,'Məhsulu seç','Bəyəndiyiniz məhsulları səbətə əlavə edin.'],[Link2,'Linki əldə et','Səbətiniz bütün məlumatları linkə çevirir.'],[MessageCircle,'Satıcıya göndər','Linki WhatsApp ilə paylaşın.']] as const;
const delivery=[
 [Truck,'2 iş günü','Sifarişlər 2 iş günü ərzində çatdırılır.'],
 [CalendarClock,'Növbəti günə qeyd','Sifarişlər növbəti günə qeyd olunur.'],
 [MapPin,'Ölkədaxili çatdırılma','Ölkədaxili ərazilərə çatdırılma mövcuddur.'],
 [TrainFront,'Metrolara pulsuz','Metrolara çatdırılma ödənişsizdir.'],
 [BadgePercent,'100 ₼-dan yuxarı pulsuz','100 manatdan yuxarı sifarişlərə çatdırılma ödənişsizdir.'],
] as const;
export default function Home(){return <><section className="container py-8 md:py-16"><div className="relative min-h-[560px] overflow-hidden rounded-[2.5rem] bg-black text-white shadow-2xl shadow-black/20"><Image src="/fon.webp" alt="" fill priority sizes="(max-width: 1280px) 100vw, 1280px" className="absolute inset-0 object-cover object-center"/><div aria-hidden="true" className="absolute inset-0 bg-[linear-gradient(105deg,rgba(0,0,0,0.92)_0%,rgba(0,0,0,0.72)_45%,rgba(0,0,0,0.35)_100%)]"/><div className="relative flex min-h-[560px] max-w-2xl flex-col justify-center p-7 sm:p-14"><span className="mb-5 text-xs font-bold uppercase tracking-[.35em] text-gray-300">Yeni kolleksiya · 2026</span><h1 className="text-5xl font-black tracking-tight sm:text-7xl">VIBE AZ</h1><p className="mt-5 text-2xl font-medium sm:text-4xl">Keyfiyyətli məhsullar bir yerdə.</p><p className="mt-5 max-w-lg text-gray-300">Seçdiyiniz məhsulları səbətə əlavə edin, xüsusi link yaradın və bir toxunuşla satıcıya göndərin.</p><Link href="/catalog" className="btn mt-8 w-fit bg-white text-black">Kataloqa bax <ArrowRight size={18}/></Link></div></div></section><section className="container py-16"><div className="mb-10 flex items-end justify-between"><div><span className="text-xs font-bold uppercase tracking-widest text-gray-500">Seçilmiş məhsullar</span><h2 className="mt-3 text-3xl font-bold sm:text-5xl">Sizin üçün seçdik</h2></div><Link href="/catalog" className="hidden font-bold sm:block">Hamısına bax →</Link></div><Catalog limit={8}/><div className="mt-10 flex justify-center"><Link href="/catalog" className="btn btn-dark w-full sm:w-auto sm:px-10">Bütün məhsullara bax <ArrowRight size={18}/></Link></div></section><section id="about" className="container py-16"><div className="overflow-hidden rounded-[2.5rem] bg-gray-100 p-8 sm:p-14"><span className="text-xs font-bold uppercase tracking-widest">Necə işləyir?</span><h2 className="mt-4 text-3xl font-bold sm:text-5xl">Sifariş üçün sadəcə bir link.</h2><div className="mt-9 grid gap-6 sm:grid-cols-3">{steps.map(([I,a,b])=><div key={a} className="flex gap-4"><span className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-black text-white"><I/></span><div><b className="text-lg">{a}</b><p className="mt-1 text-gray-600">{b}</p></div></div>)}</div><div className="mt-12 border-t border-black/10 pt-10"><span className="text-xs font-bold uppercase tracking-widest">Çatdırılma şərtləri</span><h3 className="mt-4 text-2xl font-bold sm:text-4xl">Sürətli və sərfəli çatdırılma.</h3><div className="mt-8 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{delivery.map(([I,a,b])=><div key={a} className="flex gap-4 rounded-3xl bg-white p-5"><span className="grid h-11 w-11 shrink-0 place-items-center rounded-full bg-black text-white"><I size={20}/></span><div><b>{a}</b><p className="mt-1 text-sm text-gray-600">{b}</p></div></div>)}</div></div></div></section></>}
