'use client';
import {createContext,useContext,useEffect,useState} from 'react';import {Product} from '@/data/products';
type Lang='az'|'ru'|'en';type CartItem={id:number;qty:number};
const dict={
 az:{home:'Ana səhifə',catalog:'Kataloq',about:'Haqqımızda',contact:'Əlaqə',favorites:'Seçilmişlər',cart:'Səbət',add:'Səbətə əlavə et',search:'Məhsul axtar...',empty:'Burada hələ məhsul yoxdur',category:'Kateqoriya',allCategories:'Bütün kateqoriyalar',priceMin:'Qiymət min',priceMax:'Qiymət max',sortNew:'Yeni məhsullar',sortLow:'Əvvəl ucuz',sortHigh:'Əvvəl baha',notFound:'Heç nə tapılmadı'},
 ru:{home:'Главная',catalog:'Каталог',about:'О нас',contact:'Контакты',favorites:'Избранное',cart:'Корзина',add:'Добавить в корзину',search:'Поиск товаров...',empty:'Здесь пока нет товаров',category:'Категория',allCategories:'Все категории',priceMin:'Цена от',priceMax:'Цена до',sortNew:'Новинки',sortLow:'Сначала дешёвые',sortHigh:'Сначала дорогие',notFound:'Ничего не найдено'},
 en:{home:'Home',catalog:'Catalog',about:'About',contact:'Contact',favorites:'Favorites',cart:'Cart',add:'Add to cart',search:'Search products...',empty:'No products here yet',category:'Category',allCategories:'All categories',priceMin:'Price min',priceMax:'Price max',sortNew:'Newest',sortLow:'Cheapest first',sortHigh:'Most expensive first',notFound:'Nothing found'}
};
type Ctx={cart:CartItem[];favorites:number[];lang:Lang;t:typeof dict.az;add:(p:Product)=>void;remove:(id:number)=>void;setQty:(id:number,q:number)=>void;clear:()=>void;toggleFav:(id:number)=>void;setLang:(l:Lang)=>void};
const C=createContext<Ctx|null>(null);export function StoreProvider({children}:{children:React.ReactNode}){const[cart,setCart]=useState<CartItem[]>([]),[favorites,setFavorites]=useState<number[]>([]),[lang,setLang]=useState<Lang>('az');const[ready,setReady]=useState(false);useEffect(()=>{try{setCart(JSON.parse(localStorage.getItem('vibe-cart')||'[]'));setFavorites(JSON.parse(localStorage.getItem('vibe-favs')||'[]'));setLang((localStorage.getItem('vibe-lang')as Lang)||'az')}finally{setReady(true)}},[]);useEffect(()=>{if(ready){localStorage.setItem('vibe-cart',JSON.stringify(cart));localStorage.setItem('vibe-favs',JSON.stringify(favorites));localStorage.setItem('vibe-lang',lang)}},[cart,favorites,lang,ready]);const add=(p:Product)=>setCart(c=>c.some(x=>x.id===p.id)?c.map(x=>x.id===p.id?{...x,qty:x.qty+1}:x):[...c,{id:p.id,qty:1}]);return <C.Provider value={{cart,favorites,lang,t:dict[lang],add,remove:id=>setCart(c=>c.filter(x=>x.id!==id)),setQty:(id,q)=>setCart(c=>q<1?c.filter(x=>x.id!==id):c.map(x=>x.id===id?{...x,qty:q}:x)),clear:()=>setCart([]),toggleFav:id=>setFavorites(f=>f.includes(id)?f.filter(x=>x!==id):[...f,id]),setLang}}>{children}</C.Provider>};export const useStore=()=>{const c=useContext(C);if(!c)throw new Error('Store');return c};
